name: Bug report
description: File a bug report to help us improve
title: "[BUG]"
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please provide a description of the issue you are seeing.
      placeholder: Description
    validations:
      required: true 
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Provide a description of the expected behavior.
      placeholder: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        Provide a description of the actual behavior observed. If applicable please include any error messages, exception stacktraces, or memory dumps.
      placeholder: Actual behavior
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. E.g.: the smallest possible code snippet; or a small project, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
      placeholder: Minimal Reproduction
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide more information on your environment:
          * Hosting platform or OS and Template Analyzer Version (`dotnet --info` output for .NET Core projects)
          * IDE and version : [e.g. Visual Studio 16.3]
      placeholder: Environment
    validations:
      required: false
